apiVersion: v1
kind: ConfigMap
metadata:
  name: default-backend
  namespace: {{ .Release.Namespace }}
data:
  NAME: ns1auth
  AUTH_USER: bhborkar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: {{ .Values.images.defaultbackend }}
        envFrom:
        - configMapRef:
            name: default-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: default-backend
  ports:
    - name: rest
      protocol: TCP
      port: 4001
      targetPort: 8080
---
