apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
data:
  NAME: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: {{ .Values.images.gateway }}
        envFrom:
        - configMapRef:
            name: gateway
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gateway
  ports:
    - name: rest
      protocol: TCP
      port: 4001
      targetPort: 8080
